services:
  pocket-report:
    build: .
    container_name: gwm-pocket-report
    ports:
      - "8501:8501"
    restart: "no"
    environment:
      - TZ=America/Sao_Paulo
    # volumes:
    #   - ./:/app

  nginx:
    image: nginx:alpine
    container_name: gwm-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pocket-report
    restart: always
