services:
  pocket-report:
    build: .
    container_name: gwm-pocket-report
    ports:
      - "8501:8501"
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./:/app
