services:
  pocket-report:
    build: .
    container_name: gwm-pocket-report
    ports:
      - "8501:8501"
    restart: on-failure
    environment:
      - TZ=America/Sao_Paulo
    command: >
      streamlit run app.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.baseUrlPath=ecommerce_pocket_report
      --server.enableCORS=false
      --server.enableXsrfProtection=false
